{% set name = "dace-query" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dace_query-{{ version }}.tar.gz
  sha256: ed8ccca1d3f512b09b679fec73ea48237d0708479297a1e2aff19cc06720f608

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - sphinx >=5.3.0
    - pytest >=7.2.0
  run:
    - python >=3.8
    - requests >=2.28.1
    - numpy >=1.23.4
    - pandas >=2.0.0
    - astropy >=5.1.1
    - astroquery >=0.4.5

test:
  imports:
    - dace_query
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dace.unige.ch/
  dev_url: https://github.com/astro-dace/dace-query
  summary: dace-query allows for easy querying of DACE and provides access to both public and private data through a simple utility. 
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbdelisle
