{% set name = "dace-query" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dace_query-{{ version }}.tar.gz
  sha256: ed8ccca1d3f512b09b679fec73ea48237d0708479297a1e2aff19cc06720f608

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - numpy >=1.23.4,<2.0.0
    - astropy >=5.1.1,<6.0.0
    - pandas >=1.5.1,<2.0.0
    - requests >=2.28.1,<3.0.0

test:
  imports:
    - dace_query
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dace.unige.ch/
  dev_url: https://gitlab.unige.ch/dace-public/dace-api
  summary: The dace-query lets easily query DACE and access public and private data using a simple utility tool.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbdelisle
